sudo: required
services:
  - docker
language: generic

# Remove testing section to know if Dockerfile is copied into EBS automaticlly.
# (Without COPY instruction defined in Dockerfile.dev)
# before_install:
#   - docker build -t marilyn79218/docker-react -f Dockerfile.dev .

# script:
#   - docker run -e CI=true marilyn79218/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-320583230029"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"