sudo: required
services:
  - docker

before_install:
  - docker build -t marilyn79218/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marilyn79218/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-320583230029"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_IAM_ EBS_ ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_IAM_ EBS_ SECRET_ACCESS_KEY"