sudo: required
services:
  - docker

before_install:
  - docker build -t marilyn79218/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marilyn79218/docker-react npm run test -- --coverage
